package com.radioshuddhodhan.app.core.nepalidate

// Bundled Nepali festival & holiday data for BS 2082-2084.
// Source: nepali-calendar-api by Sankalp Tharu (MIT License)
// https://github.com/S4NKALP/nepali-calendar-api — key: "BS_YEAR-BS_MONTH-BS_DAY".
// English names for recurring festivals are app-provided; data is factual calendar information.

data class HolidayInfo(
    val nameNe: String,
    val nameEn: String,
    val isPublicHoliday: Boolean
)

val NepaliHolidays: Map<String, HolidayInfo> = mapOf(
        "2082-01-01" to HolidayInfo(nameNe = "नववर्ष २०८२ आरम्भ / ललितपुर रातो मच्छिन्द्रनाथ स्नान (बुँगद्यः न्हंवः)", nameEn = "New Year", isPublicHoliday = true),
        "2082-01-02" to HolidayInfo(nameNe = "सिरूवा पावनी पर्व(सिरूवा पर्व मनाउने झापा / मोरङ)", nameEn = "सिरूवा पावनी पर्व(सिरूवा पर्व मनाउने झापा)", isPublicHoliday = false),
        "2082-01-03" to HolidayInfo(nameNe = "भक्तपुर ब्रम्हायणी यात्रा / स्वामी शशीधर जयन्ती", nameEn = "भक्तपुर ब्रम्हायणी यात्रा", isPublicHoliday = false),
        "2082-01-06" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-01-07" to HolidayInfo(nameNe = "रविसप्तमी / अष्टमीव्रत", nameEn = "रविसप्तमी", isPublicHoliday = false),
        "2082-01-08" to HolidayInfo(nameNe = "गोरखकाली पूजा / छन्द दिवस", nameEn = "गोरखकाली पूजा", isPublicHoliday = false),
        "2082-01-11" to HolidayInfo(nameNe = "बरूथिनी एकादशी / लोकतन्त्र दिवस", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-01-13" to HolidayInfo(nameNe = "माताति चःह्रे / राष्ट्रिय फोटो पत्रकारिता दिवस", nameEn = "माताति चःह्रे", isPublicHoliday = true),
        "2082-01-14" to HolidayInfo(nameNe = "मातातीर्थ औंसी / आमाको मुख हेर्ने", nameEn = "Aunsi", isPublicHoliday = false),
        "2082-01-15" to HolidayInfo(nameNe = "ललितपुर मच्छिन्द्रनाथ रथारोहण", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2082-01-16" to HolidayInfo(nameNe = "परशुराम जयन्ती", nameEn = "परशुराम जयन्ती", isPublicHoliday = false),
        "2082-01-17" to HolidayInfo(nameNe = "अक्षय तृतीया / शिवपार्वती विवाह", nameEn = "अक्षय तृतीया", isPublicHoliday = false),
        "2082-01-18" to HolidayInfo(nameNe = "विश्व श्रमिक दिवस / ललितपुर रातो मच्छिन्द्रनाथ रथ यात्रा आरम्भ", nameEn = "Labour Day", isPublicHoliday = true),
        "2082-01-19" to HolidayInfo(nameNe = "आद्यगुरु शङ्कराचार्य जयन्ती", nameEn = "आद्यगुरु शङ्कराचार्य जयन्ती", isPublicHoliday = false),
        "2082-01-20" to HolidayInfo(nameNe = "राष्ट्रिय सूचना तथा सञ्चार प्रविधि दिवस", nameEn = "National ", isPublicHoliday = true),
        "2082-01-22" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-01-23" to HolidayInfo(nameNe = "सीता जयन्ती", nameEn = "सीता जयन्ती", isPublicHoliday = false),
        "2082-01-24" to HolidayInfo(nameNe = "किराँत समाजसुधार दिवस / राष्ट्रिय पत्रकारिता दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-01-25" to HolidayInfo(nameNe = "मोहिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-01-26" to HolidayInfo(nameNe = "राष्ट्रिय कानून दिवस", nameEn = "National ", isPublicHoliday = false),
        "2082-01-27" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-01-28" to HolidayInfo(nameNe = "नृसिंह जयन्ती / स्याङ्जा लसर्घा आलमदेवी पूजा", nameEn = "नृसिंह जयन्ती", isPublicHoliday = false),
        "2082-01-29" to HolidayInfo(nameNe = "गौतमबुद्ध जयन्ती / स्वाँया पुन्हिः", nameEn = "Buddha Jayanti", isPublicHoliday = true),
        "2082-02-03" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-02-06" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-02-09" to HolidayInfo(nameNe = "अपरा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-02-10" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-02-11" to HolidayInfo(nameNe = "सिथिःचःह्रे", nameEn = "सिथिःचःह्रे", isPublicHoliday = false),
        "2082-02-13" to HolidayInfo(nameNe = "शनि जयन्ती", nameEn = "शनि जयन्ती", isPublicHoliday = false),
        "2082-02-14" to HolidayInfo(nameNe = "गोसाइँकुण्ड स्नान आरम्भ", nameEn = "गोसाइँकुण्ड स्नान आरम्भ", isPublicHoliday = false),
        "2082-02-15" to HolidayInfo(nameNe = "गणतन्त्र दिवस", nameEn = "Republic Day", isPublicHoliday = true),
        "2082-02-17" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-02-18" to HolidayInfo(nameNe = "कुमार षष्ठी / सिथीः नख", nameEn = "कुमार षष्ठी", isPublicHoliday = false),
        "2082-02-19" to HolidayInfo(nameNe = "कुमार यात्रा", nameEn = "कुमार यात्रा", isPublicHoliday = false),
        "2082-02-20" to HolidayInfo(nameNe = "वायु अष्टमी / गोरखकाली पूजा", nameEn = "वायु अष्टमी", isPublicHoliday = false),
        "2082-02-21" to HolidayInfo(nameNe = "जातीय भेदभाव तथा छुवाछुत उन्मूलन राष्ट्रिय दिवस", nameEn = "National ", isPublicHoliday = false),
        "2082-02-22" to HolidayInfo(nameNe = "गोसाइँकुण्ड स्नान समाप्ति / वैतडी विश्वनाथ मन्दिरमा गङ्गादशहरा स्नानमेला", nameEn = "गोसाइँकुण्ड स्नान समाप्ति", isPublicHoliday = false),
        "2082-02-24" to HolidayInfo(nameNe = "निर्जला एकादशी / तुलसीको दल राख्ने", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-02-27" to HolidayInfo(nameNe = "पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = false),
        "2082-02-28" to HolidayInfo(nameNe = "मष्टपूर्णिमा (ज्याःपुन्हिः) / पनौती स्नान", nameEn = "Purnima", isPublicHoliday = false),
        "2082-02-31" to HolidayInfo(nameNe = "विश्व रक्तदाता दिवस", nameEn = "Day", isPublicHoliday = true),
        "2082-03-04" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-03-05" to HolidayInfo(nameNe = "भलभल अष्टमी / देउपाटनमा त्रिशुल जात्रा", nameEn = "भलभल अष्टमी", isPublicHoliday = false),
        "2082-03-07" to HolidayInfo(nameNe = "स्मार्तहरूको योगिनी एकादशीव्रत", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-03-08" to HolidayInfo(nameNe = "वैष्णवहरुको योगिनी एकादशीव्रत / भूमिरज", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-03-10" to HolidayInfo(nameNe = "दिलाचःह्रे:", nameEn = "दिलाचःह्रे:", isPublicHoliday = false),
        "2082-03-11" to HolidayInfo(nameNe = "दर्शश्राद्ध / भूमिपूजा", nameEn = "दर्शश्राद्ध", isPublicHoliday = false),
        "2082-03-13" to HolidayInfo(nameNe = "जगन्नाथ रथयात्रा", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2082-03-14" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-03-15" to HolidayInfo(nameNe = "दहिचिउरा खाने दिन / राष्ट्रिय धान दिवस", nameEn = "दहिचिउरा खाने दिन", isPublicHoliday = false),
        "2082-03-19" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-03-21" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-03-22" to HolidayInfo(nameNe = "हरिशयनी एकादशीव्रत / तुलसी रोप्ने", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-03-26" to HolidayInfo(nameNe = "गुरू पूर्णिमा / पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = false),
        "2082-03-27" to HolidayInfo(nameNe = "विश्व जनसंख्या दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-03-28" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-03-29" to HolidayInfo(nameNe = "भानु जयन्ती", nameEn = "भानु जयन्ती", isPublicHoliday = false),
        "2082-04-01" to HolidayInfo(nameNe = "साउन संक्रान्ती / लुतो फाल्ने एवं राँको बाल्ने", nameEn = "साउन संक्रान्ती", isPublicHoliday = false),
        "2082-04-02" to HolidayInfo(nameNe = "गोरखकाली पूजा", nameEn = "गोरखकाली पूजा", isPublicHoliday = false),
        "2082-04-03" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-04-05" to HolidayInfo(nameNe = "कामिका एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-04-07" to HolidayInfo(nameNe = "घण्टाकर्ण चतुर्दशी / गठाँमुगचह्नेः", nameEn = "घण्टाकर्ण चतुर्दशी", isPublicHoliday = false),
        "2082-04-09" to HolidayInfo(nameNe = "गुँलाधर्म आरम्भ", nameEn = "गुँलाधर्म आरम्भ", isPublicHoliday = false),
        "2082-04-10" to HolidayInfo(nameNe = "चन्द्रोदय", nameEn = "चन्द्रोदय", isPublicHoliday = true),
        "2082-04-11" to HolidayInfo(nameNe = "वराह जयन्ती", nameEn = "वराह जयन्ती", isPublicHoliday = false),
        "2082-04-13" to HolidayInfo(nameNe = "नाग पञ्चमी", nameEn = "Nag Panchami", isPublicHoliday = false),
        "2082-04-14" to HolidayInfo(nameNe = "कल्की जयन्ती", nameEn = "कल्की जयन्ती", isPublicHoliday = false),
        "2082-04-15" to HolidayInfo(nameNe = "खिर खाने दिन / गोस्वामी तुलसीदास जयन्ती", nameEn = "खिर खाने दिन", isPublicHoliday = false),
        "2082-04-16" to HolidayInfo(nameNe = "अष्टमीव्रत / यल पञ्चदान", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-04-17" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-04-20" to HolidayInfo(nameNe = "पुत्रदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-04-23" to HolidayInfo(nameNe = "पूर्णिमाव्रत / बाजुरा बडिमालिका मेला", nameEn = "Purnima", isPublicHoliday = false),
        "2082-04-24" to HolidayInfo(nameNe = "जनैपूर्णिमा / ऋषितर्पणी", nameEn = "Purnima", isPublicHoliday = true),
        "2082-04-25" to HolidayInfo(nameNe = "गाईजात्रा (सापारू)(काठमाडौं उपत्यकालाई र देशभरका नेवार समुदायका लागि मात्र बिदा)", nameEn = "Gai Jatra", isPublicHoliday = false),
        "2082-04-26" to HolidayInfo(nameNe = "रोपाइँ जात्रा / यल मत्या", nameEn = "रोपाइँ जात्रा", isPublicHoliday = false),
        "2082-04-29" to HolidayInfo(nameNe = "ललितपुर नृसिंह यात्रा", nameEn = "ललितपुर नृसिंह यात्रा", isPublicHoliday = false),
        "2082-04-31" to HolidayInfo(nameNe = "श्रीकृष्णजन्माष्टमी", nameEn = "श्रीकृष्णजन्माष्टमी", isPublicHoliday = true),
        "2082-05-03" to HolidayInfo(nameNe = "अजा एकादशीव्रत / राष्ट्रिय सूचना दिवस", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-05-04" to HolidayInfo(nameNe = "स्वयम्भूको छायाँ दर्शन", nameEn = "स्वयम्भूको छायाँ दर्शन", isPublicHoliday = false),
        "2082-05-05" to HolidayInfo(nameNe = "यें पञ्चदान / जुगःच:ह्रे पुजा", nameEn = "यें पञ्चदान", isPublicHoliday = false),
        "2082-05-07" to HolidayInfo(nameNe = "कुशे औँसी / बाबुको मुख हेर्ने दिन", nameEn = "कुशे औँसी", isPublicHoliday = true),
        "2082-05-08" to HolidayInfo(nameNe = "गुलांँधर्म समाप्ति", nameEn = "गुलांँधर्म समाप्ति", isPublicHoliday = false),
        "2082-05-09" to HolidayInfo(nameNe = "दरखाने दिन", nameEn = "दरखाने दिन", isPublicHoliday = false),
        "2082-05-10" to HolidayInfo(nameNe = "हरितालिका व्रत / तीज(महिला कर्मचारीहरूको लागि मात्र बिदा)", nameEn = "Haritalika Teej", isPublicHoliday = false),
        "2082-05-11" to HolidayInfo(nameNe = "गणेश चतुर्थी", nameEn = "गणेश चतुर्थी", isPublicHoliday = false),
        "2082-05-12" to HolidayInfo(nameNe = "ऋषिपञ्चमी / विरूडा पञ्चमी", nameEn = "ऋषिपञ्चमी", isPublicHoliday = false),
        "2082-05-14" to HolidayInfo(nameNe = "गौरा सप्तमी", nameEn = "गौरा सप्तमी", isPublicHoliday = true),
        "2082-05-15" to HolidayInfo(nameNe = "गौरा पर्व(गौरा पर्व मनाउने कर्मचारीहरुका लागि मात्र बिदा)काय अष्टमी / कागेश्वर मेला", nameEn = "गौरा पर्व(गौरा पर्व मनाउने कर्मचारीहरुका लागि मात्र बिदा)काय अष्टमी", isPublicHoliday = false),
        "2082-05-18" to HolidayInfo(nameNe = "हरिपरिवर्तनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-05-19" to HolidayInfo(nameNe = "इन्द्रध्वजोत्थान / वामन द्वादशी", nameEn = "इन्द्रध्वजोत्थान", isPublicHoliday = false),
        "2082-05-20" to HolidayInfo(nameNe = "मानव वेचविखन विरुद्धको राष्ट्रिय दिवस", nameEn = "National ", isPublicHoliday = false),
        "2082-05-21" to HolidayInfo(nameNe = "ईन्द्रजात्रा(काठमाडौं उपत्यका मात्र विदा)", nameEn = "ईन्द्रजात्रा(काठमाडौं उपत्यका मात्र विदा)", isPublicHoliday = true),
        "2082-05-22" to HolidayInfo(nameNe = "यैँया पुन्हिः / चेपाङ चोनाम पर्व", nameEn = "यैँया पुन्हिः", isPublicHoliday = false),
        "2082-05-23" to HolidayInfo(nameNe = "सोह्रश्राद्ध आरम्भ / प्रतिपदा श्राद्ध", nameEn = "Sohra Shraddha", isPublicHoliday = false),
        "2082-05-24" to HolidayInfo(nameNe = "द्वितीया श्राद्ध", nameEn = "द्वितीया श्राद्ध", isPublicHoliday = false),
        "2082-05-25" to HolidayInfo(nameNe = "तृतीया श्राद्", nameEn = "तृतीया श्राद्", isPublicHoliday = false),
        "2082-05-26" to HolidayInfo(nameNe = "चतुर्थी श्राद्ध / इन्द्रध्वजपातन", nameEn = "चतुर्थी श्राद्ध", isPublicHoliday = false),
        "2082-05-27" to HolidayInfo(nameNe = "पञ्चमी श्राद्ध / षष्ठी श्राद्ध", nameEn = "पञ्चमी श्राद्ध", isPublicHoliday = false),
        "2082-05-28" to HolidayInfo(nameNe = "सप्तमी श्राद्ध", nameEn = "सप्तमी श्राद्ध", isPublicHoliday = true),
        "2082-05-29" to HolidayInfo(nameNe = "रवि सप्तमी / अष्टमीव्रत", nameEn = "रवि सप्तमी", isPublicHoliday = false),
        "2082-05-30" to HolidayInfo(nameNe = "जितिया पर्व / (जितिया पर्व मनाउने महिला कर्मचारीहरुका लागि मात्र बिदा)", nameEn = "जितिया पर्व", isPublicHoliday = false),
        "2082-05-31" to HolidayInfo(nameNe = "दशमी श्राद्ध", nameEn = "दशमी श्राद्ध", isPublicHoliday = false),
        "2082-06-01" to HolidayInfo(nameNe = "एकादशी श्राद्ध / इन्दिरा एकादशीव्रत", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-06-02" to HolidayInfo(nameNe = "द्वादशी श्राद्ध", nameEn = "द्वादशी श्राद्ध", isPublicHoliday = false),
        "2082-06-03" to HolidayInfo(nameNe = "त्रयोदशी श्राद्ध / संविधान दिवस (राष्ट्रिय दिवस)", nameEn = "त्रयोदशी श्राद्ध", isPublicHoliday = true),
        "2082-06-04" to HolidayInfo(nameNe = "चतुर्दशी श्राद्ध", nameEn = "चतुर्दशी श्राद्ध", isPublicHoliday = true),
        "2082-06-05" to HolidayInfo(nameNe = "औंसी श्राद्ध / दर्शश्राद्ध", nameEn = "Aunsi", isPublicHoliday = false),
        "2082-06-06" to HolidayInfo(nameNe = "घटस्थापना / नवरात्र आरम्भ", nameEn = "Ghatasthapana", isPublicHoliday = true),
        "2082-06-11" to HolidayInfo(nameNe = "पचली भैरव यात्रा", nameEn = "पचली भैरव यात्रा", isPublicHoliday = true),
        "2082-06-13" to HolidayInfo(nameNe = "फूलपाती / नवपत्रिका प्रवेश", nameEn = "Fulpati", isPublicHoliday = true),
        "2082-06-14" to HolidayInfo(nameNe = "महाअष्टमी / कालरात्रि", nameEn = "Maha Ashtami", isPublicHoliday = true),
        "2082-06-15" to HolidayInfo(nameNe = "महा नवमी / स्याक्वःत्याक्वः", nameEn = "महा नवमी", isPublicHoliday = true),
        "2082-06-16" to HolidayInfo(nameNe = "विजयादशमी / दर्शैको टीका २०८२", nameEn = "विजयादशमी", isPublicHoliday = true),
        "2082-06-17" to HolidayInfo(nameNe = "पापाङकुशा एकादशीव्रत / अन्नपूर्णा यात्रा", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-06-18" to HolidayInfo(nameNe = "द्वादशी", nameEn = "द्वादशी", isPublicHoliday = true),
        "2082-06-20" to HolidayInfo(nameNe = "कोजाग्रतव्रत", nameEn = "कोजाग्रतव्रत", isPublicHoliday = false),
        "2082-06-21" to HolidayInfo(nameNe = "कोजाग्रत पूर्णिमा / कतिं पुन्हिः", nameEn = "Purnima", isPublicHoliday = false),
        "2082-06-23" to HolidayInfo(nameNe = "हुलाक दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-06-25" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-06-28" to HolidayInfo(nameNe = "राधा अष्टमी / भौमाष्टमी", nameEn = "राधा अष्टमी", isPublicHoliday = false),
        "2082-06-30" to HolidayInfo(nameNe = "खाद्य दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-06-31" to HolidayInfo(nameNe = "रमा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-07-01" to HolidayInfo(nameNe = "धन्तेरस / यमदीप दान", nameEn = "धन्तेरस", isPublicHoliday = true),
        "2082-07-02" to HolidayInfo(nameNe = "काग तिहार / धन्वन्तरी जयन्ती", nameEn = "Kag Tihar", isPublicHoliday = false),
        "2082-07-03" to HolidayInfo(nameNe = "कुकुर तिहार / नरक चतुर्दशी", nameEn = "Kukur Tihar", isPublicHoliday = true),
        "2082-07-04" to HolidayInfo(nameNe = "औंसी / दर्श श्राद्ध", nameEn = "Aunsi", isPublicHoliday = true),
        "2082-07-05" to HolidayInfo(nameNe = "गाई पूजा / गोरू पूजा", nameEn = "Gai Puja", isPublicHoliday = true),
        "2082-07-06" to HolidayInfo(nameNe = "भाइटीका / किजा पूजा", nameEn = "Bhai Tika", isPublicHoliday = true),
        "2082-07-07" to HolidayInfo(nameNe = "तृतीया", nameEn = "तृतीया", isPublicHoliday = true),
        "2082-07-08" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-07-10" to HolidayInfo(nameNe = "छठ पर्व / डाला पूजा", nameEn = "Chhath", isPublicHoliday = true),
        "2082-07-12" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-07-13" to HolidayInfo(nameNe = "कुष्माण्ड नवमी", nameEn = "कुष्माण्ड नवमी", isPublicHoliday = false),
        "2082-07-14" to HolidayInfo(nameNe = "बलम्वु महालक्ष्मी यात्रा", nameEn = "बलम्वु महालक्ष्मी यात्रा", isPublicHoliday = false),
        "2082-07-15" to HolidayInfo(nameNe = "हरिबोधिनी एकादशी / तुलसी विवाह", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-07-16" to HolidayInfo(nameNe = "चाँगुनारायण अखण्डदीप दर्शन", nameEn = "चाँगुनारायण अखण्डदीप दर्शन", isPublicHoliday = false),
        "2082-07-18" to HolidayInfo(nameNe = "वैकुण्ठ चतुर्दशी", nameEn = "वैकुण्ठ चतुर्दशी", isPublicHoliday = false),
        "2082-07-19" to HolidayInfo(nameNe = "गुरूनानक जयन्ती(शिख धर्मावलम्बी कर्मचारीहरुका लागि मात्र बिदा) / पूर्णिमाव्रत", nameEn = "गुरूनानक जयन्ती(शिख धर्मावलम्बी कर्मचारीहरुका लागि मात्र बिदा)", isPublicHoliday = false),
        "2082-07-22" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-07-25" to HolidayInfo(nameNe = "फाल्गुनन्द जयन्ती(किरात धर्मावलम्बीहरूका लागि मात्र बिदा)", nameEn = "फाल्गुनन्द जयन्ती(किरात धर्मावलम्बीहरूका लागि मात्र बिदा)", isPublicHoliday = false),
        "2082-07-26" to HolidayInfo(nameNe = "बुधाष्टमीव्रत / भैरवाष्टमी", nameEn = "बुधाष्टमीव्रत", isPublicHoliday = false),
        "2082-07-28" to HolidayInfo(nameNe = "श्री गुहेश्वरी यात्रा", nameEn = "श्री गुहेश्वरी यात्रा", isPublicHoliday = false),
        "2082-07-29" to HolidayInfo(nameNe = "उत्पतिका एकादशी", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-08-02" to HolidayInfo(nameNe = "पशुपतिनाथ मेला", nameEn = "पशुपतिनाथ मेला", isPublicHoliday = false),
        "2082-08-03" to HolidayInfo(nameNe = "बाला चतुदर्शी / शतबीज छर्ने", nameEn = "बाला चतुदर्शी", isPublicHoliday = false),
        "2082-08-05" to HolidayInfo(nameNe = "टेलिभिजन दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-08-06" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-08-09" to HolidayInfo(nameNe = "विवाह पञ्चमी / जनकपुरमा सीता विवाह पञ्चमी मेला", nameEn = "विवाह पञ्चमी", isPublicHoliday = false),
        "2082-08-12" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-08-13" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-08-15" to HolidayInfo(nameNe = "मोक्षदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-08-17" to HolidayInfo(nameNe = "विश्व अपाङ्ग दिवस(अपाङ्गता भएका कर्मचारीहरूका लागि बिदा)", nameEn = "Day", isPublicHoliday = false),
        "2082-08-18" to HolidayInfo(nameNe = "यमरीपुन्हीः / उधौलीपर्व", nameEn = "यमरीपुन्हीः", isPublicHoliday = true),
        "2082-08-20" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-08-24" to HolidayInfo(nameNe = "मानव अधिकार दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-08-26" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-08-27" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-08-29" to HolidayInfo(nameNe = "सफला एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-09-05" to HolidayInfo(nameNe = "तोल ल्होसार", nameEn = "तोल ल्होसार", isPublicHoliday = true),
        "2082-09-10" to HolidayInfo(nameNe = "क्रिसमस डे", nameEn = "क्रिसमस डे", isPublicHoliday = true),
        "2082-09-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-09-13" to HolidayInfo(nameNe = "अष्टमीव्रत / सेतो मच्छिन्द्रनाथ  स्नान", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-09-15" to HolidayInfo(nameNe = "पुत्रदा एकादशी / तमुल्होछार", nameEn = "Ekadashi", isPublicHoliday = true),
        "2082-09-17" to HolidayInfo(nameNe = "सन् २०२६ आरम्भ / राष्ट्रिय टोपी दिवस", nameEn = "सन् २०२६ आरम्भ", isPublicHoliday = false),
        "2082-09-19" to HolidayInfo(nameNe = "श्रीस्वस्थानीव्रत आरम्भ / मिला पुन्हिः", nameEn = "श्रीस्वस्थानीव्रत आरम्भ", isPublicHoliday = true),
        "2082-09-21" to HolidayInfo(nameNe = "गुरु गोविन्दसिंह जयन्ती", nameEn = "गुरु गोविन्दसिंह जयन्ती", isPublicHoliday = false),
        "2082-09-23" to HolidayInfo(nameNe = "अरनिको स्मृति दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-09-24" to HolidayInfo(nameNe = "नेपाल ज्योतिष परिषद् स्थापना दिवस", nameEn = "Day", isPublicHoliday = false),
        "2082-09-26" to HolidayInfo(nameNe = "अष्टमीव्रत", nameEn = "अष्टमीव्रत", isPublicHoliday = true),
        "2082-09-27" to HolidayInfo(nameNe = "पृथ्वी जयन्ती / राष्ट्रिय एकता दिवस", nameEn = "पृथ्वी जयन्ती", isPublicHoliday = true),
        "2082-09-30" to HolidayInfo(nameNe = "षट्तिला एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-10-01" to HolidayInfo(nameNe = "माघे संक्रान्ति / माघी पर्व", nameEn = "Maghe Sankranti", isPublicHoliday = true),
        "2082-10-02" to HolidayInfo(nameNe = "राष्ट्रिय भुकम्प सुरक्षा दिवस", nameEn = "National ", isPublicHoliday = false),
        "2082-10-03" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-10-04" to HolidayInfo(nameNe = "पशुपति क्षेत्रमा माधव नारायण मेला / त्रिवेणी मेला", nameEn = "पशुपति क्षेत्रमा माधव नारायण मेला", isPublicHoliday = false),
        "2082-10-05" to HolidayInfo(nameNe = "सोनाम ल्होसार / तामाङ ल्होछार", nameEn = "Sonam Lhosar", isPublicHoliday = true),
        "2082-10-09" to HolidayInfo(nameNe = "वसन्तपञ्यमी / वसन्तश्रवण श्रीपञ्यमी सरस्वती पूजा(शिक्षण संस्थाहरूका लागि मात्र विदा)", nameEn = "वसन्तपञ्यमी", isPublicHoliday = false),
        "2082-10-10" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-10-11" to HolidayInfo(nameNe = "रवि सप्तमी / अचला सप्तमी", nameEn = "रवि सप्तमी", isPublicHoliday = false),
        "2082-10-12" to HolidayInfo(nameNe = "अष्टमीव्रत / भिष्माष्टमी", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-10-14" to HolidayInfo(nameNe = "सम्पत्ति शुद्धीकरण निवारण राष्ट्रिय दिवस", nameEn = "National ", isPublicHoliday = false),
        "2082-10-15" to HolidayInfo(nameNe = "जया एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-10-16" to HolidayInfo(nameNe = "सहिद दिवस / चाँगुमा माधव नारायण मेला", nameEn = "Day", isPublicHoliday = true),
        "2082-10-17" to HolidayInfo(nameNe = "श्री पशुपतिनाथमा छायाँ दर्शन", nameEn = "श्री पशुपतिनाथमा छायाँ दर्शन", isPublicHoliday = true),
        "2082-10-18" to HolidayInfo(nameNe = "श्रीस्वस्थानीव्रत समाप्ति / सि पुन्हिः", nameEn = "श्रीस्वस्थानीव्रत समाप्ति", isPublicHoliday = false),
        "2082-10-24" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-10-25" to HolidayInfo(nameNe = "भानु सप्तमी", nameEn = "भानु सप्तमी", isPublicHoliday = false),
        "2082-10-26" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-11-01" to HolidayInfo(nameNe = "विजया एकादशी व्रत / रेडियो दिवस", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-11-02" to HolidayInfo(nameNe = "भ्यालेन्टाइन डे", nameEn = "भ्यालेन्टाइन डे", isPublicHoliday = true),
        "2082-11-03" to HolidayInfo(nameNe = "महाशिवरात्रि / सिलाचह्रे:", nameEn = "महाशिवरात्रि", isPublicHoliday = true),
        "2082-11-06" to HolidayInfo(nameNe = "ग्याल्पो ल्होसार", nameEn = "Gyalpo Lhosar", isPublicHoliday = true),
        "2082-11-07" to HolidayInfo(nameNe = "प्रजातन्त्र दिवस / निर्वाचन दिवस", nameEn = "Democracy Day", isPublicHoliday = true),
        "2082-11-09" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-11-12" to HolidayInfo(nameNe = "भौमाष्टमीव्रत / चिरोत्थान", nameEn = "भौमाष्टमीव्रत", isPublicHoliday = false),
        "2082-11-15" to HolidayInfo(nameNe = "आमलकी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-11-16" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-11-18" to HolidayInfo(nameNe = "होली / चीरदाह", nameEn = "Holi", isPublicHoliday = false),
        "2082-11-19" to HolidayInfo(nameNe = "फागु पूर्णिमा (होलीपुन्हीः) / तराइमा होली(तराईका २१ जिल्लाहरूमा बिदा)", nameEn = "Purnima", isPublicHoliday = false),
        "2082-11-20" to HolidayInfo(nameNe = "नाला मच्छिन्द्रनाथ स्नान (नाला न्हवं)", nameEn = "नाला मच्छिन्द्रनाथ स्नान (नाला न्हवं)", isPublicHoliday = false),
        "2082-11-22" to HolidayInfo(nameNe = "नाला मच्छिन्द्रनाथ रथयात्रा", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2082-11-23" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-11-24" to HolidayInfo(nameNe = "अन्तर्राष्ट्रिय महिला दिवस", nameEn = "International ", isPublicHoliday = true),
        "2082-11-27" to HolidayInfo(nameNe = "शीतलाष्टमी / बुधाष्टमीव्रत", nameEn = "शीतलाष्टमी", isPublicHoliday = false),
        "2082-11-30" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-12-01" to HolidayInfo(nameNe = "पापमोचिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-12-03" to HolidayInfo(nameNe = "पाहाँ (पासा) चह्रे:", nameEn = "पाहाँ (पासा) चह्रे:", isPublicHoliday = false),
        "2082-12-04" to HolidayInfo(nameNe = "घोडेजात्रा(काठमाडौं उपत्यकालाई मात्र विदा)", nameEn = "घोडेजात्रा(काठमाडौं उपत्यकालाई मात्र विदा)", isPublicHoliday = false),
        "2082-12-05" to HolidayInfo(nameNe = "चोभार आदिनाथ स्नान (चोभाद्यः न्हवं)", nameEn = "चोभार आदिनाथ स्नान (चोभाद्यः न्हवं)", isPublicHoliday = false),
        "2082-12-07" to HolidayInfo(nameNe = "मत्स्येनारायण मेला / मत्स्येजयन्ती", nameEn = "मत्स्येनारायण मेला", isPublicHoliday = true),
        "2082-12-10" to HolidayInfo(nameNe = "चैती छठ", nameEn = "Chhath", isPublicHoliday = false),
        "2082-12-12" to HolidayInfo(nameNe = "चैते दशैं / सेतो मच्छिन्द्रनाथ रथयात्रा आरम्भ", nameEn = "चैते दशैं", isPublicHoliday = false),
        "2082-12-13" to HolidayInfo(nameNe = "राम नवमी / श्रीराम जयन्ती", nameEn = "राम नवमी", isPublicHoliday = true),
        "2082-12-14" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-12-15" to HolidayInfo(nameNe = "कामदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2082-12-17" to HolidayInfo(nameNe = "महावीर जयन्ती", nameEn = "महावीर जयन्ती", isPublicHoliday = false),
        "2082-12-18" to HolidayInfo(nameNe = "पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = false),
        "2082-12-19" to HolidayInfo(nameNe = "ल्हुतिपुन्हीः / वैशाख स्नान सुरू", nameEn = "ल्हुतिपुन्हीः", isPublicHoliday = false),
        "2082-12-21" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-12-22" to HolidayInfo(nameNe = "स्वामी शशिधर जयन्ती", nameEn = "स्वामी शशिधर जयन्ती", isPublicHoliday = false),
        "2082-12-27" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2082-12-28" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2082-12-30" to HolidayInfo(nameNe = "बरूथिनी एकादशीव्रत / भक्तपुर विश्वध्वजोत्थान", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-01-01" to HolidayInfo(nameNe = "नववर्ष २०८३ आरम्भ / भक्तपुर विश्वध्वजपातन (विस्काजात्रा)", nameEn = "New Year", isPublicHoliday = true),
        "2083-01-02" to HolidayInfo(nameNe = "सिरूवा पावनी पर्व(सिरूवा पर्व मनाउने झापा / मोरङ)", nameEn = "सिरूवा पावनी पर्व(सिरूवा पर्व मनाउने झापा)", isPublicHoliday = false),
        "2083-01-03" to HolidayInfo(nameNe = "भक्तपुर ब्रम्हायणी यात्रा / माताति चःह्रे पूजा", nameEn = "भक्तपुर ब्रम्हायणी यात्रा", isPublicHoliday = false),
        "2083-01-04" to HolidayInfo(nameNe = "मातातीर्थ औंसी / आमाको मुख हेर्ने", nameEn = "Aunsi", isPublicHoliday = false),
        "2083-01-05" to HolidayInfo(nameNe = "ललितपुर मच्छिन्द्रनाथ रथारोहण", nameEn = "Rath Yatra", isPublicHoliday = true),
        "2083-01-06" to HolidayInfo(nameNe = "परशुराम जयन्ती", nameEn = "परशुराम जयन्ती", isPublicHoliday = false),
        "2083-01-07" to HolidayInfo(nameNe = "अक्षय तृतीया / शिवपार्वती विवाह", nameEn = "अक्षय तृतीया", isPublicHoliday = false),
        "2083-01-08" to HolidayInfo(nameNe = "ललितपुर रातो मच्छिन्द्रनाथ रथ यात्रा आरम्भ / छन्द दिवस", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2083-01-09" to HolidayInfo(nameNe = "आद्यगुरू शंखराचार्य जयन्ती", nameEn = "आद्यगुरू शंखराचार्य जयन्ती", isPublicHoliday = false),
        "2083-01-11" to HolidayInfo(nameNe = "लोकतन्त्र दिवस", nameEn = "Day", isPublicHoliday = false),
        "2083-01-12" to HolidayInfo(nameNe = "सीता जयन्ती", nameEn = "सीता जयन्ती", isPublicHoliday = true),
        "2083-01-13" to HolidayInfo(nameNe = "राष्ट्रिय फोटो पत्रकारिता दिवस", nameEn = "National ", isPublicHoliday = false),
        "2083-01-14" to HolidayInfo(nameNe = "मोहिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-01-17" to HolidayInfo(nameNe = "नृसिंह जयन्ती / स्याङ्जा लसर्घा आलमदेवी पूजा", nameEn = "नृसिंह जयन्ती", isPublicHoliday = false),
        "2083-01-18" to HolidayInfo(nameNe = "गौतमबुद्ध जयन्ती / स्वाँया पून्हिः", nameEn = "Buddha Jayanti", isPublicHoliday = true),
        "2083-01-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-01-20" to HolidayInfo(nameNe = "राष्ट्रिय सूचना तथा सञ्चार प्रविधि दिवस", nameEn = "National ", isPublicHoliday = false),
        "2083-01-22" to HolidayInfo(nameNe = "मङ्गलचौथी व्रत", nameEn = "मङ्गलचौथी व्रत", isPublicHoliday = false),
        "2083-01-24" to HolidayInfo(nameNe = "किराँत समाजसुधार दिवस", nameEn = "Day", isPublicHoliday = false),
        "2083-01-26" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखाकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = true),
        "2083-01-30" to HolidayInfo(nameNe = "अपरा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-02-31" to HolidayInfo(nameNe = "दर्शश्राद्ध", nameEn = "दर्शश्राद्ध", isPublicHoliday = false),
        "2083-02-01" to HolidayInfo(nameNe = "सिथिः चःह्रे", nameEn = "सिथिः चःह्रे", isPublicHoliday = false),
        "2083-02-02" to HolidayInfo(nameNe = "शनि जयन्ती", nameEn = "शनि जयन्ती", isPublicHoliday = true),
        "2083-02-03" to HolidayInfo(nameNe = "अधिकमास आरम्भ / मत्स्यनारायण  मेला आरम्भ", nameEn = "अधिकमास आरम्भ", isPublicHoliday = false),
        "2083-02-09" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-02-10" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-02-12" to HolidayInfo(nameNe = "गोसाइँकुण्ड स्नान समाप्ति / वैतडी विश्वनाथ मन्दिरमा गङ्गादशहरा स्नानमेला", nameEn = "गोसाइँकुण्ड स्नान समाप्ति", isPublicHoliday = false),
        "2083-02-13" to HolidayInfo(nameNe = "पद्मिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-02-14" to HolidayInfo(nameNe = "प्रदोषव्रत", nameEn = "प्रदोषव्रत", isPublicHoliday = false),
        "2083-02-15" to HolidayInfo(nameNe = "गणतन्त्र दिवस", nameEn = "Republic Day", isPublicHoliday = true),
        "2083-02-16" to HolidayInfo(nameNe = "पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = true),
        "2083-02-17" to HolidayInfo(nameNe = "अनला पुन्हिः", nameEn = "अनला पुन्हिः", isPublicHoliday = false),
        "2083-02-21" to HolidayInfo(nameNe = "जातीय भेदभाव तथा छुवाछुत उन्मूलन राष्ट्रिय दिवस", nameEn = "National ", isPublicHoliday = false),
        "2083-02-23" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-02-24" to HolidayInfo(nameNe = "रवि सप्तमी", nameEn = "रवि सप्तमी", isPublicHoliday = false),
        "2083-02-25" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-02-28" to HolidayInfo(nameNe = "परमा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-02-29" to HolidayInfo(nameNe = "प्रदोषव्रत", nameEn = "प्रदोषव्रत", isPublicHoliday = false),
        "2083-02-30" to HolidayInfo(nameNe = "अनला चःह्रे:", nameEn = "अनला चःह्रे:", isPublicHoliday = true),
        "2083-03-01" to HolidayInfo(nameNe = "अधिकमास समाप्ती / मत्स्यनारायण मेला समाप्ति", nameEn = "अधिकमास समाप्ती", isPublicHoliday = false),
        "2083-03-06" to HolidayInfo(nameNe = "कुमार षष्ठी / सिथीःनख", nameEn = "कुमार षष्ठी", isPublicHoliday = true),
        "2083-03-07" to HolidayInfo(nameNe = "रवी सप्तमी / कुमार यात्रा", nameEn = "रवी सप्तमी", isPublicHoliday = false),
        "2083-03-08" to HolidayInfo(nameNe = "वायु अष्टमी / गोरखकाली पूजा", nameEn = "वायु अष्टमी", isPublicHoliday = false),
        "2083-03-11" to HolidayInfo(nameNe = "निर्जला एकादशी / तुलसीको दल राख्ने", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-03-13" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-03-15" to HolidayInfo(nameNe = "मष्टपूर्णिमा (ज्याःपुन्हिः) / पनौती स्नान", nameEn = "Purnima", isPublicHoliday = false),
        "2083-03-20" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-03-23" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-03-24" to HolidayInfo(nameNe = "भलभल अष्टमी / देउपाटनमा त्रिशुल जात्रा", nameEn = "भलभल अष्टमी", isPublicHoliday = false),
        "2083-03-26" to HolidayInfo(nameNe = "स्मार्तहरूको योगिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-03-27" to HolidayInfo(nameNe = "वैष्णवहरुको योगिनी एकादशी / विश्व जनसंख्या दिवस", nameEn = "Ekadashi", isPublicHoliday = true),
        "2083-03-29" to HolidayInfo(nameNe = "दिलाचःह्रे: / भानु जयन्ती", nameEn = "दिलाचःह्रे:", isPublicHoliday = false),
        "2083-03-30" to HolidayInfo(nameNe = "दर्शश्राद्ध", nameEn = "दर्शश्राद्ध", isPublicHoliday = false),
        "2083-03-32" to HolidayInfo(nameNe = "जगन्नाथ रथयात्रा", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2083-04-01" to HolidayInfo(nameNe = "साउन संक्रान्ती / लुतो फाल्ने एवं राँको बाल्ने", nameEn = "साउन संक्रान्ती", isPublicHoliday = false),
        "2083-04-02" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-04-06" to HolidayInfo(nameNe = "अष्टमीव्रत", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-04-09" to HolidayInfo(nameNe = "हरिशयनी एकादशी / तुलसी रोप्ने", nameEn = "Ekadashi", isPublicHoliday = true),
        "2083-04-13" to HolidayInfo(nameNe = "गुरू पूर्णिमा / पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = false),
        "2083-04-15" to HolidayInfo(nameNe = "खिर खाने दिन", nameEn = "खिर खाने दिन", isPublicHoliday = false),
        "2083-04-16" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-04-20" to HolidayInfo(nameNe = "अष्टमीव्रत", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-04-23" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-04-24" to HolidayInfo(nameNe = "कामिका एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-04-26" to HolidayInfo(nameNe = "घण्टाकर्ण चतुर्दशी / गथामुग चःह्रे:", nameEn = "घण्टाकर्ण चतुर्दशी", isPublicHoliday = false),
        "2083-04-28" to HolidayInfo(nameNe = "गुँलाधर्म आरम्भ", nameEn = "गुँलाधर्म आरम्भ", isPublicHoliday = false),
        "2083-04-29" to HolidayInfo(nameNe = "चन्द्रोदय", nameEn = "चन्द्रोदय", isPublicHoliday = false),
        "2083-04-30" to HolidayInfo(nameNe = "वराह जयन्ती", nameEn = "वराह जयन्ती", isPublicHoliday = true),
        "2083-05-01" to HolidayInfo(nameNe = "नाग पञ्चमी (नाग टाँस्ने)", nameEn = "Nag Panchami", isPublicHoliday = false),
        "2083-05-02" to HolidayInfo(nameNe = "कल्की जयन्ती", nameEn = "कल्की जयन्ती", isPublicHoliday = false),
        "2083-05-03" to HolidayInfo(nameNe = "गोश्वामी तुलसीदास जयन्ती / राष्ट्रिय सूचना दिवस", nameEn = "गोश्वामी तुलसीदास जयन्ती", isPublicHoliday = false),
        "2083-05-04" to HolidayInfo(nameNe = "अष्टमीव्रत / यल पञ्चदान", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-05-06" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-05-07" to HolidayInfo(nameNe = "पुत्रदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-05-11" to HolidayInfo(nameNe = "पूर्णिमाव्रत / बाजुरा बडिमालिका मेला", nameEn = "Purnima", isPublicHoliday = false),
        "2083-05-12" to HolidayInfo(nameNe = "ऋषितर्पणी / रक्षाबन्धन", nameEn = "ऋषितर्पणी", isPublicHoliday = true),
        "2083-05-13" to HolidayInfo(nameNe = "गाईजात्रा (सापारू)(काठमाडौं उपत्यकालाई र देशभरका नेवार समुदायका लागि मात्र बिदा)", nameEn = "Gai Jatra", isPublicHoliday = true),
        "2083-05-14" to HolidayInfo(nameNe = "रोपाइँ जात्रा / यल मत्या", nameEn = "रोपाइँ जात्रा", isPublicHoliday = false),
        "2083-05-16" to HolidayInfo(nameNe = "मंगल चौथी / ललितपुर नृसिंह यात्रा", nameEn = "मंगल चौथी", isPublicHoliday = false),
        "2083-05-19" to HolidayInfo(nameNe = "श्रीकृष्णजन्माष्टमी / गौरा पर्व", nameEn = "श्रीकृष्णजन्माष्टमी", isPublicHoliday = true),
        "2083-05-20" to HolidayInfo(nameNe = "मानव वेचविखन विरुद्धको राष्ट्रिय दिवस", nameEn = "National ", isPublicHoliday = true),
        "2083-05-22" to HolidayInfo(nameNe = "अजा एकादशी / निजामती सेवा दिवस", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-05-23" to HolidayInfo(nameNe = "स्वयम्भूको छायाँ दर्शन / जेनजी सहिद दिवस", nameEn = "स्वयम्भूको छायाँ दर्शन", isPublicHoliday = false),
        "2083-05-24" to HolidayInfo(nameNe = "यें पञ्चदान / जुगःचह्रे: पुजा", nameEn = "यें पञ्चदान", isPublicHoliday = false),
        "2083-05-26" to HolidayInfo(nameNe = "कुशे औँसी / बाबुको मुख हेर्ने दिन", nameEn = "कुशे औँसी", isPublicHoliday = false),
        "2083-05-27" to HolidayInfo(nameNe = "गुँलाधर्म समाप्ति", nameEn = "गुँलाधर्म समाप्ति", isPublicHoliday = true),
        "2083-05-28" to HolidayInfo(nameNe = "दरखाने दिन", nameEn = "दरखाने दिन", isPublicHoliday = false),
        "2083-05-29" to HolidayInfo(nameNe = "हरितालिका व्रत / तीज(महिला कर्मचारीहरूको लागि मात्र बिदा)", nameEn = "Haritalika Teej", isPublicHoliday = false),
        "2083-05-30" to HolidayInfo(nameNe = "मंगल चौथी / ऋषिपञ्चमीव्रत", nameEn = "मंगल चौथी", isPublicHoliday = false),
        "2083-05-31" to HolidayInfo(nameNe = "विरूडा पञ्चमी", nameEn = "विरूडा पञ्चमी", isPublicHoliday = false),
        "2083-06-01" to HolidayInfo(nameNe = "विश्वकर्मा पूजा / वास्तु दिवस", nameEn = "Vishwakarma Puja", isPublicHoliday = false),
        "2083-06-03" to HolidayInfo(nameNe = "संविधान दिवस (राष्ट्रिय दिवस) / काय  अष्टमी", nameEn = "Constitution Day", isPublicHoliday = true),
        "2083-06-06" to HolidayInfo(nameNe = "हरिपरिवर्तिनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-06-07" to HolidayInfo(nameNe = "इन्द्रध्वजोत्थान / वामन द्वादशी", nameEn = "इन्द्रध्वजोत्थान", isPublicHoliday = false),
        "2083-06-09" to HolidayInfo(nameNe = "कुमारी ईन्द्रजात्रा(काठमाडौं उपत्यका मात्र विदा) / अनन्त चतुर्दशी", nameEn = "कुमारी ईन्द्रजात्रा(काठमाडौं उपत्यका मात्र विदा)", isPublicHoliday = false),
        "2083-06-10" to HolidayInfo(nameNe = "यँया पुन्हिः / चेपाङ चोनाम पर्व", nameEn = "Indra Jatra (Yanya Punhi)", isPublicHoliday = true),
        "2083-06-11" to HolidayInfo(nameNe = "सोह्रश्राद्ध आरम्भ / प्रतिपदा श्राद्ध", nameEn = "Sohra Shraddha", isPublicHoliday = false),
        "2083-06-12" to HolidayInfo(nameNe = "द्वितीया श्राद्ध", nameEn = "द्वितीया श्राद्ध", isPublicHoliday = false),
        "2083-06-13" to HolidayInfo(nameNe = "तृतीया श्राद्ध", nameEn = "तृतीया श्राद्ध", isPublicHoliday = false),
        "2083-06-14" to HolidayInfo(nameNe = "चतुर्थी श्राद्ध / इन्द्रध्वजपातन", nameEn = "चतुर्थी श्राद्ध", isPublicHoliday = false),
        "2083-06-15" to HolidayInfo(nameNe = "पञ्चमी तथा षष्ठी श्राद्ध / राष्ट्रिय चलचित्र दिवस", nameEn = "पञ्चमी तथा षष्ठी श्राद्ध", isPublicHoliday = false),
        "2083-06-16" to HolidayInfo(nameNe = "सप्तमी श्राद्ध", nameEn = "सप्तमी श्राद्ध", isPublicHoliday = false),
        "2083-06-17" to HolidayInfo(nameNe = "अष्टमीव्रत / अष्टमी श्राद्ध", nameEn = "अष्टमीव्रत", isPublicHoliday = true),
        "2083-06-18" to HolidayInfo(nameNe = "जितिया पर्व / (जितिया पर्व मनाउने महिला कर्मचारीहरुका लागि मात्र बिदा)", nameEn = "जितिया पर्व", isPublicHoliday = false),
        "2083-06-19" to HolidayInfo(nameNe = "दशमी श्राद्ध", nameEn = "दशमी श्राद्ध", isPublicHoliday = false),
        "2083-06-20" to HolidayInfo(nameNe = "एकादशी श्राद्ध / इन्दिरा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-06-21" to HolidayInfo(nameNe = "द्वादशी श्राद्ध", nameEn = "द्वादशी श्राद्ध", isPublicHoliday = false),
        "2083-06-22" to HolidayInfo(nameNe = "त्रयोदशी श्राद्ध / जुम्ला खलङ्गामा चन्दननाथको लिङ्गो ठड्याउने", nameEn = "त्रयोदशी श्राद्ध", isPublicHoliday = false),
        "2083-06-23" to HolidayInfo(nameNe = "चतुर्दशी श्राद्ध / नःलास्वाँ चःह्रे", nameEn = "चतुर्दशी श्राद्ध", isPublicHoliday = false),
        "2083-06-24" to HolidayInfo(nameNe = "औंसी श्राद्ध / दर्शश्राद्ध", nameEn = "Aunsi", isPublicHoliday = true),
        "2083-06-25" to HolidayInfo(nameNe = "घटस्थापना / नवरात्र आरम्भ", nameEn = "Ghatasthapana", isPublicHoliday = true),
        "2083-06-29" to HolidayInfo(nameNe = "पचली भैरव यात्रा", nameEn = "पचली भैरव यात्रा", isPublicHoliday = false),
        "2083-06-31" to HolidayInfo(nameNe = "नवपत्रिका प्रवेश / फूलपाती", nameEn = "नवपत्रिका प्रवेश", isPublicHoliday = true),
        "2083-07-01" to HolidayInfo(nameNe = "महाअष्टमी / कालरात्रि", nameEn = "Maha Ashtami", isPublicHoliday = true),
        "2083-07-02" to HolidayInfo(nameNe = "जनबहाः कुछि भ्वय्", nameEn = "जनबहाः कुछि भ्वय्", isPublicHoliday = true),
        "2083-07-03" to HolidayInfo(nameNe = "महानवमी / स्याक्वःत्याक्वः", nameEn = "Maha Nawami", isPublicHoliday = true),
        "2083-07-04" to HolidayInfo(nameNe = "विजया दशमी / दशैको टिका", nameEn = "Vijaya Dashami", isPublicHoliday = true),
        "2083-07-05" to HolidayInfo(nameNe = "पापाङकुशा एकादशी / अन्नपूर्णा  यात्रा", nameEn = "Ekadashi", isPublicHoliday = true),
        "2083-07-06" to HolidayInfo(nameNe = "द्वादशी", nameEn = "द्वादशी", isPublicHoliday = true),
        "2083-07-07" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-07-08" to HolidayInfo(nameNe = "कोजाग्रतव्रत / पूर्णिमा व्रत", nameEn = "कोजाग्रतव्रत", isPublicHoliday = false),
        "2083-07-09" to HolidayInfo(nameNe = "कोजाग्रत पूर्णिमा / कतिं पुन्हिः", nameEn = "Purnima", isPublicHoliday = false),
        "2083-07-14" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-07-15" to HolidayInfo(nameNe = "रवि सप्तमी", nameEn = "रवि सप्तमी", isPublicHoliday = false),
        "2083-07-16" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-07-19" to HolidayInfo(nameNe = "रमा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-07-20" to HolidayInfo(nameNe = "धन्तेरस / यमदीप दान", nameEn = "धन्तेरस", isPublicHoliday = false),
        "2083-07-21" to HolidayInfo(nameNe = "काग तिहार / धन्वन्तरी जयन्ती", nameEn = "Kag Tihar", isPublicHoliday = true),
        "2083-07-22" to HolidayInfo(nameNe = "कुकुर तिहार / नरक चतुर्दशी", nameEn = "Kukur Tihar", isPublicHoliday = true),
        "2083-07-23" to HolidayInfo(nameNe = "औंसी / गाई पूजा", nameEn = "Aunsi", isPublicHoliday = true),
        "2083-07-24" to HolidayInfo(nameNe = "स्वःन्ति पारू / गोरू पूजा", nameEn = "स्वःन्ति पारू", isPublicHoliday = true),
        "2083-07-25" to HolidayInfo(nameNe = "भाइटीका / किजा पूजा", nameEn = "Bhai Tika", isPublicHoliday = true),
        "2083-07-26" to HolidayInfo(nameNe = "तृतीया", nameEn = "तृतीया", isPublicHoliday = true),
        "2083-07-28" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-07-29" to HolidayInfo(nameNe = "छठपर्व / डाला पूजा", nameEn = "Chhath", isPublicHoliday = true),
        "2083-08-01" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-08-02" to HolidayInfo(nameNe = "कुष्माण्ड नवमी", nameEn = "कुष्माण्ड नवमी", isPublicHoliday = false),
        "2083-08-03" to HolidayInfo(nameNe = "बलम्वु महालक्ष्मी यात्रा", nameEn = "बलम्वु महालक्ष्मी यात्रा", isPublicHoliday = false),
        "2083-08-04" to HolidayInfo(nameNe = "हरिबोधिनी एकादशी / तुलसी विवाह", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-08-05" to HolidayInfo(nameNe = "चाँगुनारायण अखण्डदीप दर्शन", nameEn = "चाँगुनारायण अखण्डदीप दर्शन", isPublicHoliday = true),
        "2083-08-07" to HolidayInfo(nameNe = "वैकुण्ठ चतुर्दशी", nameEn = "वैकुण्ठ चतुर्दशी", isPublicHoliday = false),
        "2083-08-08" to HolidayInfo(nameNe = "गुरूनानक जयन्ती(शिख धर्मावलम्बी कर्मचारीहरुका लागि मात्र बिदा) / चतुर्मासव्रत समाप्ति", nameEn = "गुरूनानक जयन्ती(शिख धर्मावलम्बी कर्मचारीहरुका लागि मात्र बिदा)", isPublicHoliday = false),
        "2083-08-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-08-15" to HolidayInfo(nameNe = "भैरवाष्टमी", nameEn = "भैरवाष्टमी", isPublicHoliday = false),
        "2083-08-17" to HolidayInfo(nameNe = "विश्व अपाङ्ग दिवस(अपाङ्गता भएका कर्मचारीहरूका लागि बिदा) / श्री गुहेश्वरी यात्रा", nameEn = "Day", isPublicHoliday = false),
        "2083-08-18" to HolidayInfo(nameNe = "उत्पत्तिका एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-08-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-08-20" to HolidayInfo(nameNe = "पशुपतिनाथ मेला", nameEn = "पशुपतिनाथ मेला", isPublicHoliday = false),
        "2083-08-21" to HolidayInfo(nameNe = "बाला चतुर्दशी / शतबीज छर्ने", nameEn = "बाला चतुर्दशी", isPublicHoliday = false),
        "2083-08-24" to HolidayInfo(nameNe = "विश्व मानव अधिकार दिवस", nameEn = "Day", isPublicHoliday = false),
        "2083-08-26" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-08-28" to HolidayInfo(nameNe = "विवाह पञ्चमी / जनकपुरमा सीता विवाह पञ्चमी मेला", nameEn = "विवाह पञ्चमी", isPublicHoliday = false),
        "2083-09-02" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-09-04" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-09-05" to HolidayInfo(nameNe = "मोक्षदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-09-08" to HolidayInfo(nameNe = "पूर्णिमाव्रत", nameEn = "Purnima", isPublicHoliday = false),
        "2083-09-09" to HolidayInfo(nameNe = "यमरीपुन्हीः / थिंला पुन्हीः", nameEn = "यमरीपुन्हीः", isPublicHoliday = true),
        "2083-09-10" to HolidayInfo(nameNe = "क्रिसमस डे", nameEn = "क्रिसमस डे", isPublicHoliday = true),
        "2083-09-11" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-09-15" to HolidayInfo(nameNe = "तमुल्होछार", nameEn = "तमुल्होछार", isPublicHoliday = true),
        "2083-09-16" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-09-17" to HolidayInfo(nameNe = "सन् २०२७ आरम्भ", nameEn = "सन् २०२७ आरम्भ", isPublicHoliday = false),
        "2083-09-18" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-09-19" to HolidayInfo(nameNe = "सफला एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-09-21" to HolidayInfo(nameNe = "गुरु गोविन्दसिंह जयन्ती", nameEn = "गुरु गोविन्दसिंह जयन्ती", isPublicHoliday = false),
        "2083-09-22" to HolidayInfo(nameNe = "दिशी चह्रे:", nameEn = "दिशी चह्रे:", isPublicHoliday = false),
        "2083-09-23" to HolidayInfo(nameNe = "अरनिको स्मृति दिवस", nameEn = "Day", isPublicHoliday = false),
        "2083-09-24" to HolidayInfo(nameNe = "तोल ल्होसार / नेपाल ज्योतिष परिषद् स्थापना दिवस", nameEn = "तोल ल्होसार", isPublicHoliday = false),
        "2083-09-25" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-09-27" to HolidayInfo(nameNe = "पृथ्वी जयन्ती / राष्ट्रिय एकता दिवस", nameEn = "पृथ्वी जयन्ती", isPublicHoliday = false),
        "2083-09-28" to HolidayInfo(nameNe = "मंगलचौथी", nameEn = "मंगलचौथी", isPublicHoliday = false),
        "2083-10-01" to HolidayInfo(nameNe = "माघे संक्रान्ति / माघी पर्व", nameEn = "Maghe Sankranti", isPublicHoliday = true),
        "2083-10-02" to HolidayInfo(nameNe = "अष्टमीव्रत / सेतो मच्छिन्द्रनाथ स्नान", nameEn = "अष्टमीव्रत", isPublicHoliday = true),
        "2083-10-04" to HolidayInfo(nameNe = "स्मार्तहरूको पुत्रदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-10-05" to HolidayInfo(nameNe = "वैष्णवहरुको पुत्रदा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-10-08" to HolidayInfo(nameNe = "श्रीस्वस्थानीव्रत आरम्भ / मिला पुन्हिः", nameEn = "श्रीस्वस्थानीव्रत आरम्भ", isPublicHoliday = false),
        "2083-10-09" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-10-12" to HolidayInfo(nameNe = "मंगल चौथी", nameEn = "मंगल चौथी", isPublicHoliday = false),
        "2083-10-15" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-10-16" to HolidayInfo(nameNe = "सहिद दिवस", nameEn = "Day", isPublicHoliday = true),
        "2083-10-19" to HolidayInfo(nameNe = "षटतिला एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-10-22" to HolidayInfo(nameNe = "लैंचह्रे:", nameEn = "लैंचह्रे:", isPublicHoliday = false),
        "2083-10-23" to HolidayInfo(nameNe = "पशुपति क्षेत्रमा माधव नारायण मेला / त्रिवेणी मेला", nameEn = "पशुपति क्षेत्रमा माधव नारायण मेला", isPublicHoliday = true),
        "2083-10-24" to HolidayInfo(nameNe = "सोनाम ल्होसार / तामाङ ल्होछार", nameEn = "Sonam Lhosar", isPublicHoliday = true),
        "2083-10-28" to HolidayInfo(nameNe = "वसन्तपञ्यमी / वसन्तश्रवण श्रीपञ्यमी सरस्वती पूजा(शिक्षण संस्थाहरूका लागि मात्र विदा)", nameEn = "वसन्तपञ्यमी", isPublicHoliday = false),
        "2083-11-01" to HolidayInfo(nameNe = "विश्व रेडियो दिवस / अचला सप्तमी", nameEn = "Day", isPublicHoliday = true),
        "2083-11-02" to HolidayInfo(nameNe = "अष्टमीव्रत / भिष्माष्टमी", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-11-05" to HolidayInfo(nameNe = "भीमा एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-11-06" to HolidayInfo(nameNe = "चाँगुमा माधव नारायण मेला", nameEn = "चाँगुमा माधव नारायण मेला", isPublicHoliday = false),
        "2083-11-07" to HolidayInfo(nameNe = "राष्ट्रिय प्रजातन्त्र दिवस / निर्वाचन दिवस", nameEn = "Democracy Day", isPublicHoliday = true),
        "2083-11-08" to HolidayInfo(nameNe = "श्रीस्वस्थानीव्रत समाप्ति / सि पुन्हिः", nameEn = "श्रीस्वस्थानीव्रत समाप्ति", isPublicHoliday = true),
        "2083-11-15" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-11-16" to HolidayInfo(nameNe = "अष्टमीव्रत / गोरखकाली पूजा", nameEn = "अष्टमीव्रत", isPublicHoliday = false),
        "2083-11-18" to HolidayInfo(nameNe = "माझी समुदायको लदी पूजा", nameEn = "माझी समुदायको लदी पूजा", isPublicHoliday = false),
        "2083-11-20" to HolidayInfo(nameNe = "विजया एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-11-22" to HolidayInfo(nameNe = "महाशिवरात्रि / सिलाचह्रे:", nameEn = "महाशिवरात्रि", isPublicHoliday = true),
        "2083-11-24" to HolidayInfo(nameNe = "अन्तर्राष्ट्रिय महिला दिवस", nameEn = "International ", isPublicHoliday = true),
        "2083-11-25" to HolidayInfo(nameNe = "ग्याल्पो ल्होसार", nameEn = "Gyalpo Lhosar", isPublicHoliday = true),
        "2083-11-29" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-12-02" to HolidayInfo(nameNe = "भौमाष्टमीव्रत / चिरोत्थान", nameEn = "भौमाष्टमीव्रत", isPublicHoliday = false),
        "2083-12-04" to HolidayInfo(nameNe = "आमलकी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-12-06" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-12-07" to HolidayInfo(nameNe = "होली / चीरदाह", nameEn = "Holi", isPublicHoliday = false),
        "2083-12-08" to HolidayInfo(nameNe = "फागु पूर्णिमा (होलीपुन्हीः) / तराइमा होली(तराईका २१ जिल्लाहरूमा बिदा)", nameEn = "Purnima", isPublicHoliday = false),
        "2083-12-09" to HolidayInfo(nameNe = "नाला मच्छिन्द्रनाथ स्नान  (नाला न्हवं)", nameEn = "नाला मच्छिन्द्रनाथ स्नान  (नाला न्हवं)", isPublicHoliday = false),
        "2083-12-10" to HolidayInfo(nameNe = "विश्व क्षयरोग दिवस", nameEn = "Day", isPublicHoliday = false),
        "2083-12-11" to HolidayInfo(nameNe = "नाला मच्छिन्द्रनाथ रथयात्रा", nameEn = "Rath Yatra", isPublicHoliday = false),
        "2083-12-13" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-12-16" to HolidayInfo(nameNe = "शीतलाष्टमी / गोरखकाली पूजा", nameEn = "शीतलाष्टमी", isPublicHoliday = false),
        "2083-12-19" to HolidayInfo(nameNe = "पापमोचनी एकादशी", nameEn = "Ekadashi", isPublicHoliday = false),
        "2083-12-20" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-12-22" to HolidayInfo(nameNe = "पाहाँ (पासा) चह्रे:", nameEn = "पाहाँ (पासा) चह्रे:", isPublicHoliday = false),
        "2083-12-23" to HolidayInfo(nameNe = "घोडे जात्रा(काठमाडौं उपत्यकालाई मात्र बिदा)", nameEn = "घोडे जात्रा(काठमाडौं उपत्यकालाई मात्र बिदा)", isPublicHoliday = false),
        "2083-12-24" to HolidayInfo(nameNe = "चोभार आदिनाथ स्नान (चोभाद्यः न्हवं)", nameEn = "चोभार आदिनाथ स्नान (चोभाद्यः न्हवं)", isPublicHoliday = false),
        "2083-12-26" to HolidayInfo(nameNe = "मत्स्येनारायण मेला / मत्स्येजयन्ती", nameEn = "मत्स्येनारायण मेला", isPublicHoliday = false),
        "2083-12-27" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2083-12-29" to HolidayInfo(nameNe = "चैती छठ", nameEn = "Chhath", isPublicHoliday = false),
        "2083-12-30" to HolidayInfo(nameNe = "भक्तपुर विश्वध्वजोत्थान", nameEn = "भक्तपुर विश्वध्वजोत्थान", isPublicHoliday = false),
        "2084-01-04" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-01-11" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-01-18" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-01-25" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-02-01" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-02-08" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-02-15" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-02-22" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-02-29" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-03-05" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-03-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-03-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-03-26" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-04-01" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-04-08" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-04-15" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-04-22" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-04-29" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-05-05" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-05-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-05-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-05-26" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-06-02" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-06-09" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-06-16" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-06-23" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-06-30" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-07-07" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-07-14" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-07-21" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-07-28" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-08-05" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-08-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-08-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-08-26" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-09-03" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-09-10" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-09-17" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-09-24" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-10-02" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-10-09" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-10-16" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-10-23" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-10-30" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-11-07" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-11-14" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-11-21" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-11-28" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-12-05" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-12-12" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-12-19" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
        "2084-12-26" to HolidayInfo(nameNe = "सार्वजनिक बिदा", nameEn = "Public Holiday", isPublicHoliday = true),
)